CREATE DATABASE [MelodyMakerDB] ON  PRIMARY 
( NAME = N'MelodyMakerDB', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MelodyMakerDB.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MelodyMakerDB_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\MelodyMakerDB_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [MelodyMakerDB] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [MelodyMakerDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MelodyMakerDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MelodyMakerDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MelodyMakerDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MelodyMakerDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MelodyMakerDB] SET  READ_WRITE 
GO
ALTER DATABASE [MelodyMakerDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MelodyMakerDB] SET  MULTI_USER 
GO
ALTER DATABASE [MelodyMakerDB] SET PAGE_VERIFY CHECKSUM  
GO
USE [MelodyMakerDB]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [MelodyMakerDB] MODIFY FILEGROUP [PRIMARY] DEFAULT

go 
Create Table tblMood
(
moodID int primary key identity(1,1),
moodName varchar(20),
moodDesc varchar(50),
)

go 
Create Table tblGenre
(
genreID int primary key identity(1,1),
genreName varchar(20),
genreDesc varchar(50),
)
go 
Create Table tblCSV
(
csvID int primary key identity(1,1),
csvName varchar(20),
csvPath varchar(50),
genreID int unique references tblGenre(genreID),
moodID int unique references tblMood(moodID),
)