/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comDb;

import static comDb.UpdateDetails.sUsername;
import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author Nicolas
 */
public class ChooseHostel extends javax.swing.JFrame {
    Connection conn = null;
    OraclePreparedStatement pst = null;
    OracleResultSet rs = null;
    
    
    /**
     * Creates new form ChooseHostel
     */
    public ChooseHostel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLeuwen = new javax.swing.JButton();
        btnHassels = new javax.swing.JButton();
        btnGenk = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLeuwen.setText("Leuwen");
        btnLeuwen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeuwenActionPerformed(evt);
            }
        });

        btnHassels.setText("Hassels");
        btnHassels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHasselsActionPerformed(evt);
            }
        });

        btnGenk.setText("Genk");
        btnGenk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenkActionPerformed(evt);
            }
        });

        jLabel1.setText("Choose your hostel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnLeuwen)
                        .addGap(26, 26, 26)
                        .addComponent(btnHassels)
                        .addGap(32, 32, 32)
                        .addComponent(btnGenk))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeuwen)
                    .addComponent(btnHassels)
                    .addComponent(btnGenk))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeuwenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeuwenActionPerformed
        conn = ConnectionClass.ConnectDB();
        try{
            String sql = "Insert into tbl_Students(Hostel) VALUES('Leuwen') WHERE Student_name="+sUsername;
            rs = (OracleResultSet) pst.executeQuery(sql);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Congrats, Your Hostel is now Leuwen!");
                Portal p = new Portal(sUsername);
                p.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Something went wrong, Hostel not chosen.");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }                                         
    }//GEN-LAST:event_btnLeuwenActionPerformed

    private void btnHasselsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHasselsActionPerformed
        conn = ConnectionClass.ConnectDB();
        try{
            String sql = "Insert into tbl_Students(Hostel) VALUES('Leuwen') WHERE Student_name="+sUsername;
            rs = (OracleResultSet) pst.executeQuery(sql);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Congrats, Your Hostel is now Hassals!");
                Portal p = new Portal(sUsername);
                p.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Something went wrong, Hostel not chosen.");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnHasselsActionPerformed

    private void btnGenkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenkActionPerformed
        conn = ConnectionClass.ConnectDB();
        try{
            String sql = "Insert into tbl_Students(Hostel) VALUES('Genk') WHERE student_name="+sUsername;
            rs = (OracleResultSet) pst.executeQuery(sql);
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Congrats, Your Hostel is now Genk!");
                Portal p = new Portal(sUsername);
                p.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Something went wrong, Hostel not chosen.");
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnGenkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseHostel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseHostel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseHostel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseHostel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseHostel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenk;
    private javax.swing.JButton btnHassels;
    private javax.swing.JButton btnLeuwen;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
